services:
  db:
    image: pgvector/pgvector:pg17
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: talkdai
      POSTGRES_PASSWORD: talkdai
      POSTGRES_DB: talkdai
    volumes:
       - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "talkdai", "-U", "talkdai"]
      interval: 10s
      timeout: 5s
      retries: 5
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - '3000:8080'
    environment:
      - OPENAI_API_KEYS=FAKE-KEY;
      - OPENAI_API_BASE_URLS=http://dialog:8000/openai;
      - ENABLE_OPENAI_API=true
      - DATABASE_URL=postgresql://talkdai:talkdai@db/talkdai
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      db:
        condition: service_healthy

volumes:
  open-webui:
  postgres: