[project]
name = "jdn-chunk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "markitdown[all]>=0.1.1",
    "ollama>=0.4.8",
]
